//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragDropPhoneApp.ResourceStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DragDropPhoneApp.ResourceStrings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2558909828-qsFXEywYd2xjGo1b9pIANFvMjN2ANAOiSPsp2mp.
        /// </summary>
        public static string AccesToken {
            get {
                return ResourceManager.GetString("AccesToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29shsDxbFt0Koy17jygoxWeLN7jzapiNLOvki90lDtxIf.
        /// </summary>
        public static string AccesTokenSecret {
            get {
                return ResourceManager.GetString("AccesTokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to riMI9rvmpxdyQWFAJvxzUsusm.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5eqgOqF1Ca2fUSL8MwZaL6F3GW5xlTKLEbHph46HUs0iLrPtL2.
        /// </summary>
        public static string APIsecret {
            get {
                return ResourceManager.GetString("APIsecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images.
        /// </summary>
        public static string ImageFolder {
            get {
                return ResourceManager.GetString("ImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/.
        /// </summary>
        public static string ImageFolderSlash {
            get {
                return ResourceManager.GetString("ImageFolderSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:61252/api/routesapi.
        /// </summary>
        public static string uriRoutesApi {
            get {
                return ResourceManager.GetString("uriRoutesApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:61252/api/userapi.
        /// </summary>
        public static string uriUserApi {
            get {
                return ResourceManager.GetString("uriUserApi", resourceCulture);
            }
        }
    }
}
